"""
CropGuard AI — Configuration
All tuneable parameters live here — no hardcoded thresholds anywhere else.
"""
import os
from pathlib import Path

# Project root (one level above this file)
ROOT_DIR = Path(__file__).resolve().parent.parent


class Config:
    # ------------------------------------------------------------------ #
    #  Security                                                            #
    # ------------------------------------------------------------------ #
    SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-secret-key-change-before-production')

    # ------------------------------------------------------------------ #
    #  Database — SQLite for dev, easy swap to PostgreSQL via DATABASE_URL #
    # ------------------------------------------------------------------ #
    _db_path = ROOT_DIR / 'cropguard.db'
    SQLALCHEMY_DATABASE_URI = os.environ.get(
        'DATABASE_URL',
        f'sqlite:///{_db_path}'
    )
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    # pool_pre_ping only applies to non-SQLite DBs; SQLite ignores it gracefully
    SQLALCHEMY_ENGINE_OPTIONS = {
        'pool_pre_ping': True,
    }

    # ------------------------------------------------------------------ #
    #  ML Model                                                            #
    # ------------------------------------------------------------------ #
    # Path to trained model checkpoint (relative to project root)
    MODEL_PATH = os.environ.get(
        'MODEL_PATH',
        str(ROOT_DIR / 'models' / 'mobilenetv2_plantvillage.pth')
    )
    # Path to class-label JSON (generated by training/train.py)
    CLASSES_PATH = os.environ.get(
        'CLASSES_PATH',
        str(ROOT_DIR / 'models' / 'classes.json')
    )

    # ------------------------------------------------------------------ #
    #  Confidence Abstention — THE configurable threshold                  #
    #  If model confidence < this value, we refuse to return a label.     #
    #  Tune per-crop in production via env var or DB override.            #
    # ------------------------------------------------------------------ #
    CONFIDENCE_THRESHOLD = float(os.environ.get('CONFIDENCE_THRESHOLD', 0.85))

    # ------------------------------------------------------------------ #
    #  Demo / Development Mode                                             #
    #  Set DEMO_MODE=false after running training/train.py                #
    # ------------------------------------------------------------------ #
    DEMO_MODE = os.environ.get('DEMO_MODE', 'true').lower() == 'true'

    # ------------------------------------------------------------------ #
    #  File Upload                                                         #
    # ------------------------------------------------------------------ #
    MAX_CONTENT_LENGTH = 16 * 1024 * 1024   # 16 MB hard cap
    UPLOAD_FOLDER = str(ROOT_DIR / 'uploads')
    ALLOWED_EXTENSIONS = {'jpg', 'jpeg', 'png', 'webp'}

    # ------------------------------------------------------------------ #
    #  External APIs                                                       #
    # ------------------------------------------------------------------ #
    # Open-Meteo (free, no API key required)
    WEATHER_API_BASE = 'https://api.open-meteo.com/v1/forecast'
    WEATHER_TIMEOUT_S = 5  # seconds

    # ------------------------------------------------------------------ #
    #  Outbreak Detection (Phase 3)                                        #
    # ------------------------------------------------------------------ #
    OUTBREAK_MIN_CLUSTER_SIZE = int(os.environ.get('OUTBREAK_MIN_CLUSTER_SIZE', 3))
    OUTBREAK_RADIUS_KM = float(os.environ.get('OUTBREAK_RADIUS_KM', 50.0))
    OUTBREAK_WINDOW_DAYS = int(os.environ.get('OUTBREAK_WINDOW_DAYS', 7))

    # ------------------------------------------------------------------ #
    #  Debug                                                               #
    # ------------------------------------------------------------------ #
    DEBUG = os.environ.get('FLASK_DEBUG', 'true').lower() == 'true'
    TESTING = False


class ProductionConfig(Config):
    """Production overrides — set via environment variables."""
    DEBUG = False
    DEMO_MODE = False
    TESTING = False
    # PostgreSQL: set DATABASE_URL=postgresql://user:pass@host/dbname
    # Model:      set MODEL_PATH and CLASSES_PATH to cloud storage paths


class TestingConfig(Config):
    TESTING = True
    SQLALCHEMY_DATABASE_URI = 'sqlite:///:memory:'
    DEMO_MODE = True
    WTF_CSRF_ENABLED = False


# Map name → class for factory use
config_by_name = {
    'development': Config,
    'production': ProductionConfig,
    'testing': TestingConfig,
    'default': Config,
}
